-- Email-safe logo URL — separates the canonical logo (whatever the org uploads)
-- from the rasterized PNG that email clients can reliably render. Generated
-- automatically by the regenerate-email-logo edge function.
-- Applied via Supabase MCP on 2026-05-11.

ALTER TABLE organizations
  ADD COLUMN IF NOT EXISTS logo_email_url TEXT;

COMMENT ON COLUMN organizations.logo_email_url IS
  'Email-safe rasterized PNG of the logo. Generated by the regenerate-email-logo edge function from logo_url. Email templates should prefer this column.';

-- J2S backfill: keep canonical SVG in logo_url, point logo_email_url at the
-- already-rasterized PNG (uploaded during the 2026-05-11 marketing-send work).
UPDATE organizations
  SET logo_url       = 'https://iuasfpztkmrtagivlhtj.supabase.co/storage/v1/object/public/org-assets/j2s-logo.svg',
      logo_email_url = 'https://iuasfpztkmrtagivlhtj.supabase.co/storage/v1/object/public/org-assets/j2s-logo.png'
  WHERE id = '1adf10ad-d091-4aa0-82e3-af331468ea2b';
