-- Wire up fee pass-through (operator can pass the 1% platform fee to families).
--
-- Safety: default flips to FALSE so operators ABSORB the fee unless they
-- deliberately opt in via the Finances toggle. (Previously defaulted true,
-- which would have charged every new operator's families a fee by default.)
--
-- No snapshot column: checkout AND process-installments read live org config
-- for the fee (matching how platform_fee_*_pct already work — see
-- computePlatformFee.ts), so pass-through mode is read live too. Toggling
-- mid-installment-plan affects in-flight installments 2/3, same as a rate
-- change would; operators are told not to toggle mid-term.
ALTER TABLE organizations ALTER COLUMN fee_pass_through SET DEFAULT false;
