-- Drops public_read_districts. SUPERSEDED IN THE SAME PASS by 20260813d, which
-- recreates it scoped `to anon`. Both are applied; read them as one change.
--
-- WHY IT IS SPLIT RATHER THAN REWRITTEN: this one was applied to prod before I
-- understood the policy, and rewriting an applied migration to look like it was
-- always right would hide the sequence that actually ran. It ran, it was wrong
-- for four minutes, and 20260813d fixed it.
--
-- WHAT WAS ACTUALLY WRONG. public_read_districts is `to public`, which includes
-- `authenticated`. Postgres ORs policies together, so it overrode the org-scoped
-- org_access_districts beside it and any operator could read every active org's
-- districts. Measured on staging: an operator owning 1 district could read all 8.
--
-- WHAT I GOT WRONG. I concluded the policy served nothing, because I grepped for
-- `.from("districts")` and found only /admin callers. The public registration
-- catalog reads it as a POSTGREST EMBED —
--   program_locations?select=...,districts(name)
-- — which never contains the string I searched for. 20260806d states this in its
-- own header, which I had not read at that point. Dropping the policy broke the
-- district grouping on every public catalog until 20260813d restored it.
--
-- The defect was the ROLE, not the policy. Grep finds; reading confirms.

drop policy if exists public_read_districts on public.districts;
